// LCD + Audio (SAI/WM8994) per STM32F746G-DISCOVERY
#define HAL_LTDC_MODULE_ENABLED
#define HAL_SAI_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_SDRAM_MODULE_ENABLED
#define HAL_FMC_MODULE_ENABLED
#define HAL_DMA2D_MODULE_ENABLED
#define HAL_DMA_MODULE_ENABLED
